spring:
  application:
    name: seged

  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:seged}
      username: ${SPRING_DATA_MONGODB_USERNAME:admin}
      password: ${SPRING_DATA_MONGODB_PASSWORD:admin123}
      authentication-database: admin

    redis:
      host: localhost
      port: 6380
      password: ${SPRING_DATA_REDIS_PASSWORD:}

server:
  port: 8080

app:
  session:
    ttl: PT2M

jwt:
  expiration: 28800000

jms:
  queue:
    product: product.queue
